---
abstract: 'HTML::TreeBuilder::XPath compatible interface with libxml'
author:
  - 'Tokuhiro Matsuno <tokuhirom  slkjfd gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-TreeBuilder-LibXML
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  XML::LibXML: 1.69
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
