---
abstract: 'HTML::TreeBuilder and XPath compatible interface with libxml'
author:
  - 'Tokuhiro Matsuno <tokuhirom  slkjfd gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.03'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-TreeBuilder-LibXML
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::TreeBuilder::XPath: 0.14
  XML::LibXML: 1.7
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.16
